apiVersion: v1
kind: Pod
metadata:
  name: reverse-proxy
spec:
  containers:
  - name: caddy
    image: docker.io/caddy:latest
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: tcp
    - containerPort: 443
      hostPort: 8443
      
      protocol: tcp
    volumeMounts:
    - name: reverse-proxy-config
      mountPath: /etc/caddy
      readOnly: true
    - name: reverse-proxy-data
      mountPath: /data
  volumes:
  - name: reverse-proxy-config
    configMap:
      name: reverse-proxy-config
      items:
      - key: Caddyfile
        path: Caddyfile
  - name: reverse-proxy-data
    persistentVolumeClaim:
      claimName: reverse_proxy_data
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reverse-proxy-config
data:
    Caddyfile: |
      rpi.remi.calixte.eu {
              encode gzip

              header Strict-Transport-Security max-age=15552000;
              reverse_proxy http://10.0.2.2:5080
      }
