apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
spec:
  containers:
  - name: app
    image: docker.io/library/nextcloud:fpm-alpine
    env:
    - name: MYSQL_DATABASE
      value: nextcloud
    - name: MYSQL_USER
      value: nextcloud
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-passwords
          key: mysql_password
    - name: MYSQL_HOST
      value: "127.0.0.1"
    - name: REDIS_HOST
      value: "127.0.0.1"
    volumeMounts:
      - name: nextcloud-html
        mountPath: /var/www/html
      - name: nextcloud-data
        mountPath: /var/www/html/data:z
  - name: redis
    image: docker.io/library/redis:alpine
    args:
    - --save ""
  - name: mariadb
    image: docker.io/library/mariadb:10
    args:
    - --transaction-isolation=READ-COMMITTED
    - --log-bin=binlog
    - --binlog-format=ROW
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-passwords
          key: mysql_root_password
    - name: MYSQL_DATABASE
      value: nextcloud
    - name: MYSQL_USER
      value: nextcloud
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-passwords
          key: mysql_password
    volumeMounts:
      - name: nextcloud-db
        mountPath: /var/lib/mysql
  - name: caddy
    image: docker.io/caddy:latest
    ports:
    - containerPort: 80
      hostPort: 5080
      protocol: tcp
    volumeMounts:
    - name: caddy-config
      mountPath: /etc/caddy
      readOnly: true
    - name: caddy-data
      mountPath: /data
    - name: nextcloud-html
      mountPath: /var/www/html
      readOnly: true
  volumes:
  - name: caddy-config
    configMap:
      name: caddy-config
      items:
      - key: Caddyfile
        path: Caddyfile
  - name: caddy-data
    persistentVolumeClaim:
      claimName: caddy_data
  - name: nextcloud-html
    persistentVolumeClaim:
      claimName: nextcloud_html
  - name: nextcloud-db
    persistentVolumeClaim:
      claimName: nextcloud_db
  - name: nextcloud-data
    hostPath:
      path: /data/nextcloud
      type: Directory
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
    Caddyfile: |
      :80 {

              root * /var/www/html
              file_server

              php_fastcgi 127.0.0.1:9000

              redir /.well-known/carddav /remote.php/dav 301
              redir /.well-known/caldav /remote.php/dav 301

              # .htaccess / data / config / ... shouldn't be accessible from outside
              @forbidden {
                      path    /.htaccess
                      path    /data/*
                      path    /config/*
                      path    /db_structure
                      path    /.xml
                      path    /README
                      path    /3rdparty/*
                      path    /lib/*
                      path    /templates/*
                      path    /occ
                      path    /console.php
              }

              respond @forbidden 404

      }
